### ISSUE TITLE
When executing step "Make"

### ISSUE THREAD

**Issue by lulpie** [emqtt/qmqtt-client#13]
Hi I'm pretty new to QtCreator and after downloading the files i still have trouble running it. I am on linux raspberry pi. I also do not understand the steps on making a library, my main.cpp file for #include "qmqtt.h" states that no directory is found .I hope someone can help resolve my issue. Thank you.

**Comment by mwallnoefer** [comment]
This description is very superfluous, since you don't mention the exact steps and error messages. Have a try reading the README of https://github.com/emqtt/qmqtt, maybe this helps for better comprehension.

As you have told us that your code should run under a Raspberry Pi, cross compilation will likely be a key aspect since you compile on the PC, not on the device. Is that correct?

**Comment by lulpie** [comment]
The following error is what popped up on the compiler section of qt when it was runned" When executing step "Make" ". And no I compiled it on rasberry pi itselt, not on PC.

**Comment by lulpie** [comment]
The following error is what popped up on the compiler section of qt when it was runned" When executing step "Make" ". And no I compiled it on rasberry pi itselt, not on PC.

**Comment by lulpie** [comment]
The following error is what popped up on the compiler section of qt when it was runned" When executing step "Make" ". And no I compiled it on rasberry pi itselt, not on PC.

**Comment by lulpie** [comment]
The following error is what popped up on the compiler section of qt when it
was runned" When executing step "Make" ". And no I didn't compile it on PC.

**Comment by mwallnoefer** [comment]
You should provide us a screenshot or a log of the whole build, since the single line
```
When executing step "Make" 
```
does not help us.
